### ISSUE TITLE
Could resolve host

### ISSUE THREAD

**Issue by amon28** [ProjectInfinity/PocketVote-PocketMine#1]
Whenever I add a link to the vote 
It says this on the console
[PocketVote] VoteCheckTask: Couldn't resolve host 'api.pocketvote.io'

**Comment by ProjectInfinity** [comment]
What are you running your server on?

**Comment by amon28** [comment]
I'm running on tesseract

**Comment by ProjectInfinity** [comment]
What is tesseract? I need to know what operating system you are running the server on.

**Comment by amon28** [comment]
Oh I'm running my server on my phone

**Comment by ProjectInfinity** [comment]
You need a real server, running PocketMine on phones won't work with any plugin that requires internet access.

There's no way I or anyone else can support something like PocketVote on your phone.

**Comment by amon28** [comment]
Ok
