### ISSUE TITLE
[16:59:42] [Server thread/INFO]: There are no added links, use /guadd [url] to add a link! vote [16:59:52] [Server thread/INFO]: You can add a link by typing /guadd [16:59:52] [Server thread/INFO]: See /guru for help!

### ISSUE THREAD

**Issue by captainleviftw** [ProjectInfinity/PocketVote-PocketMine#11]
`[16:59:42] [Server thread/INFO]: There are no added links, use /guadd [url] to add a link!
vote
[16:59:52] [Server thread/INFO]: You can add a link by typing /guadd
[16:59:52] [Server thread/INFO]: See /guru for help!`

What link shall I add?

**Comment by ProjectInfinity** [comment]
See /guru for help. It's meant for voting links.

**Comment by captainleviftw** [comment]
so like /guadd <server voting link website??

**Comment by ProjectInfinity** [comment]
Yep.

**Comment by captainleviftw** [comment]
Is it just this or what https://minecraftpocket-servers.com

**Comment by ProjectInfinity** [comment]
It's whatever link you want. So yes.
