### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Wertzui123** [ProjectInfinity/PocketVote-PocketMine#13]
Hey, what does [IMPORTANT!!] Multi-server support is now handled on PocketVote backend, MySQL support has been removed mean? How can I use multi server support now, without any config?

**Comment by ProjectInfinity** [comment]
Go to your server settings on PocketVote.io and click the connected servers button. Whatever is checked will also receive a vote when the selected server receives one.

This system is also more flexible in that you can allow any of your other servers to also send votes to other servers.

**Comment by Wertzui123** [comment]
Thanks
