### ISSUE TITLE
Item not given when player votes

### ISSUE THREAD

**Issue by AL3XPI** [ProjectInfinity/PocketVote-PocketMine#14]
I have it set so that if a player is online and votes, it will "give player diamond 1". That's the literal command. The voting is setup properly as whenever someone votes it does, "say thanks for voting us on site, player!" However the player does not recieve the diamond upon voting and in the console log it says: 
![image](https://user-images.githubusercontent.com/35903333/62215001-1a47c480-b374-11e9-8406-1e4c88f91157.png)
Please help me with this.

**Comment by ProjectInfinity** [comment]
I'm guessing the player has spaces in his name. That is almost universally
unsupported in plugins as far as I know. This is not a pocketvote issue.

**Comment by AL3XPI** [comment]
Oh ok, I tried voting (my name has no spaces) and it worked. So thank you for notifying me of that @ProjectInfinity
