### ISSUE TITLE
Pocketvote crashed server

### ISSUE THREAD

**Issue by McNeil9028** [ProjectInfinity/PocketVote-PocketMine#15]
Error: Cannot use object of type stdClass as array
File: plugins/PocketVote-PocketMine.phar/src/ProjectInfinity/PocketVote/task/TopVoterTask
Line: 57
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PocketVote v3.0.1

Code:
[48] 
[49]     public function onCompletion(Server $server): void {
[50]         if(!$this->hasResult()) {
[51]             $server->getLogger()->error('[PocketVote] TopVoterTask - Failed to retrieve top voters. Try again later.');
[52]             return;
[53]         }
[54] 
[55]         $result = $this->getResult();
[56] 
[57]         if(!$result['success'] && isset($result['error'])) {
[58]             $server->getLogger()->error('[PocketVote] TopVoterTask - An error occurred while contacting the PocketVote servers, please try again later.');
[59]             $server->getLogger()->error('[PocketVote] curl error occurred during TopVoterTask: '.$result['error']);
[60]             return;
[61]         }
[62] 
[63]         if(!$result['success']) {
[64]             $server->getLogger()->error('[PocketVote] TopVoterTask - An error occurred while contacting the PocketVote servers, please try again later.');
[65]             return;
[66]         }
[67] 

Backtrace:
#0 src/pocketmine/scheduler/AsyncPool(320): ProjectInfinity\PocketVote\task\TopVoterTask->onCompletion(object pocketmine\Server)
#1 src/pocketmine/Server(2573): pocketmine\scheduler\AsyncPool->collectTasks()
#2 src/pocketmine/Server(2345): pocketmine\Server->tick()
#3 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
#4 src/pocketmine/Server(1784): pocketmine\Server->start()
#5 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[59] /home/minecraft/multicraft/servers/server156111/pocketmine/, string[67] /home/minecraft/multicraft/servers/server156111/pocketmine/plugins/)
#6 src/pocketmine/PocketMine(299): pocketmine\server()
#7 (1): require(string[115] phar:///home/minecraft/multicraft/servers/server156111/pocketmine/jar/pocketmine)

PocketMine-MP version: 3.9.4 [Protocol 361]
Git commit: 1be6783c34ec51b578464899994285a7e8188590
uname -a: Linux DFW1-1102 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64
PHP Version: 7.3.8
Zend version: 3.3.8
OS : Linux, linux

Loaded plugins:
EnchantUI 0.5 by UnknownOre for API(s) 3.0.0
iProtector 3.1-PCP by LDX for API(s) 3.0.0, 3.5.2, 4.0.0
PureEntitiesX 0.6.3 by milk0417, RevivalPMMP for API(s) 3.9.0
BlazinVanish 1.0.4 by iiFlamiinBlaze for API(s) 3.0.0
MCPEToDiscord 1.4 by Jackthehaxk21 for API(s) 3.0.0
BlockSniper 3.2.3 by BlockHorizons, Sandertv (@Sandertv), Chris-Prime (@PrimusLV) for API(s) 3.2.0
MobStacker 0.2.3 by UnknownOre for API(s) 3.8.1
EssentialsPE 2.1.0 by LegendsOfMCPE Team for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
MyStats 1.4.13 by CzechMPDevs, VixikCZ for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
PCFly 3.0.0 by Angel for API(s) 3.0.0
PocketVote 3.0.1 by ProjectInfinity for API(s) 3.0.0
Texter 3.2.1 by yuko_fuyutsuki, mfmfnek0, onebone, ogiwara, Shootsta_ERU0531, Toganon, ShadowArt, Marron0421 for API(s) 3.9.0
Slapper 1.5.0 by jojoe77777 for API(s) 3.9.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
FactionsProBeta 1.4.11 by Tethered_ for API(s) 3.0.0
Minion 1.0.0 by xXNiceYT for API(s) 3.0.0
BuycraftPM 2.0.1 by Tebex Limited for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
EnderPearlCooldown 0.0.2 by AdminConfirmed for API(s) 3.8.2
BankNotes 2.0.3 by AndreasHGK for API(s) 3.7.0
PiggyCustomEnchants 1.4.6 by DaPigGuy for API(s) 3.2.0
Worlds 2.1.0 by survanetwork for API(s) 3.0.0
StairSeat 1.4.0 by korado531m7 for API(s) 3.9.0
SimpleReplies 1.0.2 by jasonwynn10 for API(s) 3.0.0
essentialsTP 1.2.2 by  for API(s) 3.0.0
SellAll 1.3.0 by AndreasHGK for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
ChestShop 2.2.5 by MinecrafterJPN for API(s) 3.0.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.0.0
DevTools 1.13.4 by PocketMine Team for API(s) 3.4.0
RenameItems 1.1 by Wertzui123 for API(s) 3.0.0
MiningRewards 1.5 by David for API(s) 3.0.0
PurePerms 1.4.2-c2a by 64FF00 & ProjectInfinity for API(s) 3.0.0
MysteryCrate 9.1.1 by JackMD, DaPigGuy for API(s) 3.9.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
EasyKits 1.0.0 by AndreasHGK for API(s) 3.9.0

**Comment by joeymcneil** [comment]
server is 
Play.mcfactions.world
25565

**Comment by ProjectInfinity** [comment]
Sorry about the late response. Please try this development build and let me know how it works.
https://poggit.pmmp.io/r/65370/PocketVote-PocketMine_dev-54.phar
