### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by MonoAdrian23** [ProjectInfinity/PocketVote-PocketMine#16]
PocketMine-MP Crash Dump Thu Feb 27 20:00:47 CET 2020

Error: Cannot use object of type stdClass as array
File: plugins/PocketVote-PocketMine.phar/src/ProjectInfinity/PocketVote/task/TopVoterTask
Line: 57
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PocketVote v3.0.1

Code:

Backtrace:
#0 src/pocketmine/scheduler/AsyncPool(304): ProjectInfinity\PocketVote\task\TopVoterTask->onCompletion(object pocketmine\Server)
#1 src/pocketmine/Server(2384): pocketmine\scheduler\AsyncPool->collectTasks()
#2 src/pocketmine/Server(2143): pocketmine\Server->tick()
#3 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#4 src/pocketmine/Server(1584): pocketmine\Server->start()
#5 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#6 src/pocketmine/PocketMine(296): pocketmine\server()
#7 (11): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.11.6 [Protocol 389]
Git commit: cb9e79b3985719671bd5cbaa7f665b04a6d33359-dirty
uname -a: Linux e6ca3bd9d403 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u1~bpo9+1 (2019-09-30) x86_64
PHP Version: 7.3.6
Zend version: 3.3.6
OS : Linux, linux

**Comment by 95CivicSi** [comment]
@ProjectInfinity I was helping another server get with this problem and discovered that it was only happening when the server was already crashing.  In my case, the first crash was caused by a config file that had incorrect entries in the `onvote:` section.

```yaml
onvote:
- give %player% 432 1
```
This issue and #15 are most likely caused by the same problem.

**Comment by ProjectInfinity** [comment]
This build should fix your issue.
https://poggit.pmmp.io/r/65370/PocketVote-PocketMine_dev-54.phar
