### ISSUE TITLE
error with api3/block branch

### ISSUE THREAD

**Issue by optimusprime338** [ProjectInfinity/PocketVote-PocketMine#2]
api git commit:- db12657
plugin commit:- 3407150
error with debug report:-(dawn to op)
25.07 14:43:06 [Server] Server thread/DEBUG #8 /PocketMine-MP.phar(1): require_once(string phar:///PocketMine-MP.phar/src/pocketmine/PocketMine.php)
25.07 14:43:06 [Server] Server thread/DEBUG #7 src/pocketmine/PocketMine(511): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///PocketMine-MP.phar/, string /, string /plugins/)
25.07 14:43:06 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1680): pocketmine\Server->start()
25.07 14:43:06 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2098): pocketmine\Server->tickProcessor()
25.07 14:43:06 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2219): pocketmine\Server->tick()
25.07 14:43:06 [Server] Server thread/DEBUG #3 src/pocketmine/Server(2454): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 7505)
25.07 14:43:06 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/ServerScheduler(325): pocketmine\scheduler\TaskHandler->run(integer 7505)
25.07 14:43:06 [Server] Server thread/DEBUG #1 src/pocketmine/scheduler/TaskHandler(154): ProjectInfinity\PocketVote\task\SchedulerTask->onRun(integer 7505)
25.07 14:43:06 [Server] Server thread/DEBUG #0 PocketVote-PocketMine.phar/src/ProjectInfinity/PocketVote/task/SchedulerTask(20): pocketmine\{closure}(integer 8, string Undefined property: ProjectInfinity\PocketVote\PocketVote::$identity, string phar:///plugins/PocketVote-PocketMine.phar/src/ProjectInfinity/PocketVote/task/SchedulerTask.php, integer 20, array Array())
25.07 14:43:06 [Server] Server thread/CRITICAL ErrorException: "Undefined property:

**Comment by ProjectInfinity** [comment]
Can you send me a link to the exact page where you got your PocketMine phar?

**Comment by optimusprime338** [comment]
https://poggit.pmmp.io/ci/pmmp/PocketMine-MP/~/dev:1256

**Comment by ProjectInfinity** [comment]
What's the difference between this and the master branch?

**Comment by ProjectInfinity** [comment]
The PHAR at the link you provided works fine for me. Please make sure your identity and secret is correctly set in your config.yml file.

**Comment by ProjectInfinity** [comment]
It's been 10 days since I saw any activity from you. I will consider this ticket closed, feel free to open a new ticket if this is still an issue.
