### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by jhoe241** [ProjectInfinity/PocketVote-PocketMine#22]
[Server thread/CRITICAL]: Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "plugins/PocketVot
e-PocketMine.phar/src/ProjectInfinity/PocketVote/task/TopVoterTask" at line 57

**Comment by ProjectInfinity** [comment]
This build should fix your issue.
https://poggit.pmmp.io/r/65370/PocketVote-PocketMine_dev-54.phar
