### ISSUE TITLE
 [PocketVote] An error occurred while getting vote link. [PocketVote] Curl error: error setting certificate verify locations: CAfile: /home/container/plugin_data/PocketVote/cacert.pem CApath: none

### ISSUE THREAD

**Issue by BariPlayzYT** [ProjectInfinity/PocketVote-PocketMine#25]
[PocketVote] An error occurred while getting vote link.
 [PocketVote] Curl error: error setting certificate verify locations: CAfile: /home/container/plugin_data/PocketVote/cacert.pem CApath: none

**Comment by ProjectInfinity** [comment]
You can download the following file manually and put it in the PocketVote data folder.
https://curl.haxx.se/ca/cacert.pem
