### ISSUE TITLE
Sorry to come back so soon, but none of the builds are working for me (ALPHA6)

### ISSUE THREAD

**Issue by Little2Epic** [ProjectInfinity/PocketVote-PocketMine#3]
I get a "[12:26:48] [Server thread/ERROR]: Could not load 'C:\Users\Little2Epic\Documents\PocketMine-MP\plugins\PocketVote-PocketMine.phar' in folder 'C:\Users\Little2Epic\Documents\PocketMine-MP\plugins\': yaml_parse(): reading error encountered during parsing: control characters are not allowed (line 1, column 1)" I dunno what specifically it means, and I even tried to fork to fix some stuff, but I get the same errors.

**Comment by ProjectInfinity** [comment]
Can you remove the identity and secret from your config.yml and post it to pastebin?

**Comment by Little2Epic** [comment]
Okay.

**Comment by Little2Epic** [comment]
https://pastebin.com/cJgBegDJ

**Comment by ProjectInfinity** [comment]
Are you sure this is an issue? The configuration you provided works perfectly fine.

**Comment by Little2Epic** [comment]
What version does Alpha 7 run might I ask?

**Comment by ProjectInfinity** [comment]
This server is running PocketMine-MP 1.6.2dev+poggit.1250 「Unleashed」 implementing API version 3.0.0-ALPHA7 for Minecraft: PE v1.1.0.55 (protocol version 113)

Is what it says. I do not play MCPE, so I have no idea. Try Alpha7.

**Comment by Little2Epic** [comment]
I'd love to, but at the moment my power is out. I'll report back wheb it's on, so I'll leave the thread open.

**Comment by Little2Epic** [comment]
It's working fine.
