### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by coolkidsrule101** [ProjectInfinity/PocketVote-PocketMine#4]
make this plugin as a ui system for fast easy  use age

**Comment by ProjectInfinity** [comment]
What kind of ui are you think about? What would it do?

**Comment by armagadon159753** [comment]
@ProjectInfinity  FormAPI

**Comment by ProjectInfinity** [comment]
@armagadon159753 I need more information. What would it do? I don't know where form api fits in.

**Comment by optimusprime338** [comment]
I don't think there is any need for UI! Players don't have to do anything with plugin in game!!

**Comment by HimbeersaftLP** [comment]
>I don't think there is any need for UI! Players don't have to do anything with plugin in game!!

^

**Comment by ProjectInfinity** [comment]
Yeah, I agree with the above messages. I can't imagine what good a UI would do, if you have a really good reason then I'd love to hear it but until then I think the UI you get through the PocketVote site serves it's purpose (which I'd like to expand on as well with better statistics and such).

**Comment by Haxley** [comment]
Maybe they just want a canvas to describe their vote rewards as opposed to making signs or something. You could make UI that shows a button for each vote site, then you tap it to see the rewards and/or description. Check KitUI for example. Again, no real need other than it being an alternative way for server owners to describe voting and vote rewards.

**Comment by optimusprime338** [comment]
Or to show how many total times they voted ?? And plus how many times they voted This month? Some people use rank points !! Why not embed that into it?? So this does that same??

**Comment by optimusprime338** [comment]
It could be handy a explanatry form pops up for how to vote and where ?coz lots of new kids are usually confused what to do!!

**Comment by ProjectInfinity** [comment]
I feel like these things could easily be achieved with just a command and its output.

**Comment by ProjectInfinity** [comment]
UI works has begun.

Since this issue was started creating UIs have become very effortless and it seems to be fairly stable.
Will try to find some use cases where it makes more sense to use a UI over chat log (like top voter list for instance, it may be hard to display more than 10 users in chat without it getting lost if the chat is very busy).
