### ISSUE TITLE
VoteCheckTask

### ISSUE THREAD

**Issue by artulloss** [ProjectInfinity/PocketVote-PocketMine#6]
[21:09:30] [Server thread/ERROR]: [PocketVote] VoteCheckTask: SSL: couldn't create a context: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers

**Comment by ProjectInfinity** [comment]
Reinstall PocketMine AND the PHP binaries.

**Comment by artulloss** [comment]
Would updating the phar be adequate? I also don't know where to get the binaries and I can't figure out how to compile them on my pc.

**Comment by ProjectInfinity** [comment]
No that is not enough. Do not compile anything, you need to download the PocketMine PHP binaries again.

**Comment by artulloss** [comment]
Ok, I'll reinstall them from here: https://jenkins.pmmp.io/job/PHP-7.2-Aggregate/
