### ISSUE TITLE
x2 votes

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [ProjectInfinity/PocketVote-PocketMine#7]
Wen a player join, all commands are run x2 times sometimes, just today i added the plugin , so there is no way for players to not claim a vote for 2 days and then collect all.....

**Comment by ProjectInfinity** [comment]
How many sites are you using with PocketVote and post your config.yml file after removing your identity, secret and mysql credentials (if you use that).

**Comment by TDMidkwhatisxd** [comment]
---
dev: false
version: 4
identity: 
secret: 
lock: true
vote-expiration: 7
multi-server:
  enabled: false
  role: master
  mysql:
    host: ~
    port: 0
    username: ~
    password: ~
    database: ~
onvote:
  run-cmd: []
  online-cmd:
  - givemoney "%player" 10000
  - say §9 %player voted at§a %site §9, and he got 10.000$ + cool rewards !
  - give "%player" diamond 10
  - give "%player" wood 10
  - give "%player" steak 10
  - give "%player" iron_ingot 10
votes:
- player: 'BestSamiLyne '
  site: minecraftpocket-servers.com
  ip: 
  expires: 1523370491
...

**Comment by TDMidkwhatisxd** [comment]
just 1 site i use

**Comment by TDMidkwhatisxd** [comment]
Do u know how i set /vote  ? i don't understand what link to add to guru , so players gets reward on join , so maybe that is a problem?

**Comment by TDMidkwhatisxd** [comment]
i think i know, vote check task , and onjoin vote , run at same time?

**Comment by TDMidkwhatisxd** [comment]
Gave $10000 to Pro 9000000000
[14:55:10] [Server thread/INFO]: [Server]  Pro 9000000000 voted at minecraftpocket-servers.com , and he got 10.000$ + cool rewards !
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Diamond (264:0) * 10 to Pro 9000000000]
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Oak Wood (17:0) * 10 to Pro 9000000000]
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Steak (364:0) * 10 to Pro 9000000000]
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Iron Ingot (265:0) * 10 to Pro 9000000000]
[14:55:10] [Server thread/INFO]: Gave $10000 to Pro 9000000000
[14:55:10] [Server thread/INFO]: [Server]  Pro 9000000000 voted at minecraftpocket-servers.com , and he got 10.000$ + cool rewards !
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Diamond (264:0) * 10 to Pro 9000000000]
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Oak Wood (17:0) * 10 to Pro 9000000000]
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Steak (364:0) * 10 to Pro 9000000000]
[14:55:10] [Server thread/INFO]: [CONSOLE: Given Iron Ingot (265:0) * 10 to Pro 9000000000]

**Comment by TDMidkwhatisxd** [comment]
+ there is a problem, some players don't exit wen they vote, they need to relogin to can claim

**Comment by TDMidkwhatisxd** [comment]
votes:
- player: 'BestSamiLyne '
  site: minecraftpocket-servers.com
  ip: -
  expires: 1523370491
- player: ProF Kral1
  site: minecraftpocket-servers.com
  ip: -
  expires: 1523372698
- player: FlimsyGalaxy505
  site: minecraftpocket-servers.com
  ip: -
  expires: 1523372970



ummm why first player have  name between   ' and other names don't ? ummmm

**Comment by TDMidkwhatisxd** [comment]
I think you should .... Check if player voted first, Remove Players from cfg and last give rewards

**Comment by TDMidkwhatisxd** [comment]
In onjoin is spammed bt client, u will get reward many times until is removed .... my guess

**Comment by ProjectInfinity** [comment]
This behavior is not normal. Try using a different PocketMine build. Which version are you using of pocketvote?

**Comment by TDMidkwhatisxd** [comment]
I found out the problem

**Comment by TDMidkwhatisxd** [comment]
Latest/Latest
The problem was this   public function onVoteEvent(VoteEvent $event) {
After i deleted it, bug got fixed

**Comment by TDMidkwhatisxd** [comment]
I tested on my local server , adding in config my vote info , again and again ... ill do some tests and i will move the plugin on my server ....

**Comment by ProjectInfinity** [comment]
Oh... I don't support pocketvote instances that have been modified. You just removed the code that handles all votes.

**Comment by TDMidkwhatisxd** [comment]
Did you read what i just saying ? I removed to fix ...  Omg

**Comment by ProjectInfinity** [comment]
The plugin is working fine for over a hundred thousand servers... It should work for you too.

**Comment by TDMidkwhatisxd** [comment]
This plugin don't work fine on latest pmmp , and is weird ... i don't recommend using it, is a mess ....
Those thousand servers are just leet.cc servers :)

**Comment by ProjectInfinity** [comment]
There's still tens of thousands of servers that aren't leet servers which use pocketvote. It works fine for them too.

You can send me a link to where you found your PocketMine build and I can take a look but chances are it'll work just fine.
