### ISSUE TITLE
ErroR on Console

### ISSUE THREAD

**Issue by Wolfkid200444** [ProjectInfinity/PocketVote-PocketMine#9]
a hello Project Infinity I'm getting this kind of errors in my console

> [PocketVote] An error occurred while getting vote link

> 14:54:31[Server thread/ERROR]:  [PocketVote] VoteCheckTask: Could not resolve host: api.pocketvote.io

> [PocketVote] Curl error: Could not resolve host: mcpe.guru

**Comment by ProjectInfinity** [comment]
Make sure your server has access to the Internet.

What operating system is your server running on?

**Comment by Wolfkid200444** [comment]
Do u Mean Host?

**Comment by ProjectInfinity** [comment]
Yes

**Comment by Wolfkid200444** [comment]
Well I'm using  MineHud.de

**Comment by Wolfkid200444** [comment]
>#Properties Config file
>#Fri Aug 3 07:04:49 CEST 2018
>motd=PocketMine-MP Server
>server-port=25748
>white-list=0
>announce-player-achievements=off
>spawn-protection=500
>max-players=55
>allow-flight=on
>spawn-animals=on
>spawn-mobs=on
>gamemode=0
>force-gamemode=off
>hardcore=off
>pvp=on
>difficulty=1
>generator-settings=
>level-name=FacMap
>level-seed=
>level-type=DEFAULT
>enable-query=on
>enable-rcon=on
>rcon.password=
>auto-save=on
>view-distance=8
xbox-auth=on
online-mode=on
>op-permission-level=1
>allow-nether=off
>spawn-monsters=off
>spawn-npcs=off
>generate-structures=off
>enable-command-block=off
>server-ip=
>query.port=
>rcon.port=

This??

**Comment by ProjectInfinity** [comment]
Try asking them to check if the host can reach https://api.pocketvote.io
and https://mcpe.guru
